### ISSUE TITLE
Speeds not improved with increased cores on DICE and MBP

### ISSUE THREAD

**Issue by kungfujam** [CSTR-Edinburgh/mlpractical#6] opened 2015-09-28 13:44 UTC
Running the second code block to test increasing cores gives me no improvement on DICE. I've also installed all packages with anaconda on a macbook pro and tested this. Should I be expecting a greater speedup with increased cores?

See screenshots of results and configs here:
https://www.dropbox.com/sh/qjqbp64zml7y6jl/AAC9waew2a1DAdIQ7z1bh8raa?dl=0

**Comment by pswietojanski** [comment] 2015-09-29 09:54
Just to confirm, are you using OpenBLAS on DICE and OpenBLAS/MKL on MBP?

**Comment by kungfujam** [comment] 2015-09-29 14:39
Set up as instructed on Dice, i.e. with openblas. Mac set up with anaconda
academic licence having downloaded MKL. See the config images for
verification of what is installed/being used.

**Comment by kungfujam** [comment] 2015-10-01 11:29
Just to update, I've completely rerun with the new instructions. Results in same place and issue still there. Perhaps the program is simply not taxing enough to show benefit?

**Comment by pswietojanski** [comment] 2015-10-01 11:33
Looks like the first setup was still using atlas (based on the screens), but for MKL you should notice a difference. I did not have time to have a look at this but yes, it's quite possible the problem isn't large enough.

**Comment by srenals** [comment] 2015-10-01 11:45
I think XCode on mac includes Apple's version of BLAS and LAPACK, so it may well be that default builds of numpy are OK.  
https://developer.apple.com/library/mac/documentation/Accelerate/Reference/AccelerateFWRef/index.html#//apple_ref/doc/uid/TP40009465 <https://developer.apple.com/library/mac/documentation/Accelerate/Reference/AccelerateFWRef/index.html#//apple_ref/doc/uid/TP40009465>

sorry for not thinking of this earlier....

> On 1 Oct 2015, at 12:33, Pawel Swietojanski <notifications@github.com> wrote:
> 
> Looks like the first setup was still using atlas (based on the screens), but for MKL you should notice a difference. I did not have time to have a look at this but yes, it's quite possible the problem isn't large enough.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CSTR-Edinburgh/mlpractical/issues/6#issuecomment-144702627>.
> 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by pswietojanski** [comment] 2015-10-01 17:53
OK, so the reason for this is, timeit in notebook can only measure total cell timing, not the particular calls. You should get reasonable numbers that show the actual speed-up by defining defning something like below but in separate cells:

os.environ['OMP_NUM_THREADS'] = str(1)
%%timeit numpy.dot(x,x.T)

next cell here:

os.environ['OMP_NUM_THREADS'] = str(2)
%%timeit numpy.dot(x,x.T)

**Comment by kungfujam** [comment] 2015-10-02 11:31
Is the same problem apparent if we just use the time package? I altered the code and still have the same issue...

```
import os
import multiprocessing
import time
import numpy as np

num_cores = multiprocessing.cpu_count()
N = 2000
x = np.random.random((N,N))
loops = 10

for i in xrange(0, num_cores):
    t = np.zeros(loops)
    # first, set the number of threads OpenBLAS
    # should use, the below line is equivalent
    # to typing export OMP_NUM_THREADS=i+1 in bash shell
    print 'Running %d-by-%d matrix-matrix product on %i core(s)' % (N, N, (i + 1))
    os.environ['OMP_NUM_THREADS'] = str(i+1)
    for j in xrange(0, loops):
        start = time.time()
        null = np.dot(x,x.T)
        t[j] = time.time() - start
    print 
    meantime = np.mean(t) * 1000 # http://www.meantimebrewing.com/
    mintime = np.min(t) * 1000
    print "%d loops, mean: %0.1f ms per loop, min: %0.1f ms per loop" % (loops, meantime, mintime)

# reset the number of threads used
os.environ['OMP_NUM_THREADS'] = '1'
```

Output:
```
Running 2000-by-2000 matrix-matrix product on 1 core(s)

10 loops, mean: 364.7 ms per loop, min: 359.4 ms per loop
Running 2000-by-2000 matrix-matrix product on 2 core(s)

10 loops, mean: 363.0 ms per loop, min: 359.4 ms per loop
Running 2000-by-2000 matrix-matrix product on 3 core(s)

10 loops, mean: 363.0 ms per loop, min: 359.4 ms per loop
Running 2000-by-2000 matrix-matrix product on 4 core(s)

10 loops, mean: 363.5 ms per loop, min: 359.4 ms per loop
```

**Comment by matt-graham** [comment] 2016-11-05 21:36
Closing this as the updated first lab notebook doesn't include a comparison against number of cores running on.

**Closed by matt-graham** 2016-11-05 21:36 UTC
